# s=input("S:")
# s=s.split()
# print(f"Số từ trong chuỗi la:",len(s))
# max_len = max(len(x) for x in s)
# m = tuple(x for x in s if len(x) == max_len)
# print("Các từ dài nhất trong xâu là:")
# print(m)
# s=input("S:")
# s=s.split()
# print(f"So tu trong chuỗi la: ",len(s))
# dainhat=max(len(x) for x in s)
# m=", ".join(x for x in s if len(x)==dainhat)
# print("So tu dai nhat la: ")
# print(m)

s=input("S:")
s=s.split()
print(s)
m="-".join(x for x in s)
print(m)